### ISSUE TITLE
Mods talk while channel is frozen

### ISSUE THREAD

**Issue by EMRG-Fluff** [JulianusIV/LathBot#27]
Allowing mods to talk in a frozen channel, both to say why channel was frozen, if needed, and unfreeze the channel without the need for an admin to unfreeze it.

**Comment by JulianusIV** [comment]
- [ ] add mod role to chats to overwrite the freeze
- [ ] change unfreeze to admin only (to prevent abuse

**Comment by JulianusIV** [comment]
Plagues are now able to type during a freeze, but unfreezing will remain in control of the admins to prevent abuse.
