### ISSUE TITLE
sticker sniping

### ISSUE THREAD

**Issue by Hamfisher** [JulianusIV/LathBot#38]
**Describe the bug**
You can't snipe a sticker

**To Reproduce**
1. Post a sticker
2. Delete it
3. Use -snipe
4. Profit

**Expected behavior**
It shows you the deleted sticker?

**Screenshots**
What about an epic jump link
 https://discord.com/channels/699555747591094344/721107980455641180/936243956981829684

**Plaftorm (please complete the following information):**
 - Mobile - No
 - Browser - Discord app?
 - Client - My discord is as updated as possible? (i'm being useless and it will stay that way)

**Additional context**
Fixing this is probably a waste of your time

**Comment by Hamfisher** [comment]
i dunno how browser helps if im using the app

**Comment by JulianusIV** [comment]
> i dunno how browser helps if im using the app

That was just to ask what platfor you are using out of the three lol

**Comment by Hamfisher** [comment]
> > i dunno how browser helps if im using the app
> 
> That was just to ask what platform you are using out of the three lol

i don't know the platforms my brain doesn't extend that far

**Comment by JulianusIV** [comment]
> > > i dunno how browser helps if im using the app
> > 
> > That was just to ask what platform you are using out of the three lol
> 
> i don't know the platforms my brain doesn't extend that far

...

 - Discord mobile
 - Dicord as an application
 - Or discord in the browser

The three things that were listed

**Comment by JulianusIV** [comment]
But in any case, i am unsure if its possible to send stickers from servers lathbot has no access to, but ill have to look into it

**Comment by JulianusIV** [comment]
Wontfix, because bots cant use stickers from servers they are not in, and stickers are not available as image links like emojis are
