### ISSUE TITLE
Lathbot is able to embed images in venting channel

### ISSUE THREAD

**Issue by Hamfisher** [JulianusIV/LathBot#46]
**Describe the bug**
You can use lathbot to embed things into the venting channel,

**To Reproduce**
1. Go to venting channel
2. Tell Lathbot to -repeat an image
3. Lathbot embeds the image

**Expected behavior**
Probably shouldn't be able to embed things with lathbot when you cannot embed things normally

**Screenshots**
(I deleted the -repeat command)
![image](https://user-images.githubusercontent.com/98070343/177229970-fa3a8222-49f9-4574-813d-48fda562deff.png)

**Plaftorm (please complete the following information):**
_**Client**_

**Comment by JulianusIV** [comment]
Fixed by treating venting the same as debate
