### ISSUE TITLE
Lathbot is inconsistent in determining links in debate 

### ISSUE THREAD

**Issue by equablecomet801** [JulianusIV/LathBot#47]
It is inconsistent Because in the recent discussion of weapons and caliber it would occasionally detect the caliber as a link or not

**To Reproduce**
1. Go to 'debate'
2. Type something and add a space then a .22 and maybe something after it
3. It might detect it as a link

**Expected behavior**
It doesn't detect calibers and units of measurement as a link

**Plaftorm (please complete the following information):**
 - Mobile
 - Browser
 - Client

**Comment by JulianusIV** [comment]
fixed with next update by rolling back a regex change
