### ISSUE TITLE
I broke Lathbot in debate again 

### ISSUE THREAD

**Issue by equablecomet801** [JulianusIV/LathBot#49]
**Describe the bug**
Lathbot didn't fully remove YouTube link

**To Reproduce**
1. Go to '#debat'
2. link a YouTube video that had it's link copied on the Mobile app(Android YouTube app)

**Expected behavior**
LathBot didn't fully remove the link 

**Screenshots**
![Screenshot_2022-09-21-00-05-15-015](https://user-images.githubusercontent.com/102339195/191419056-cb4501a5-ebc8-44fd-9508-425ec641930b.jpg)

**Plaftorm (please complete the following information):**
 - Mobile

**Comment by JulianusIV** [comment]
not reproducable for now
